### ISSUE TITLE
Chunks rendered wrong on entering a dimension

### ISSUE THREAD

**Issue by tahg** [Darkhax-Minecraft/Ore-Stages#15] opened 2018-04-25 09:34 UTC
When entering a new dimension, the current chunk section (at least) is rendered before the Game Stages data is set.  I reported a similar issue in Item Stages, and this may fundamentally be an issue with Game Stages itself.  In my particular case (on SevTech 3.0.6), I entered a dimension containing ladders at the spawn in point, and they require a stage (which I have).  Their bounding and collision boxes are correct but they are rendered as wood planks.  A block update that causes the chunk to rerender makes them look correct.

**Comment by darkhax** [comment] 2018-04-25 16:16
Yes, this is a fundamental issue with GameStages. It's caused by a race condition with the update packet being delayed. I've opened up [this](https://github.com/Darkhax-Minecraft/Game-Stages/issues/15) issue so I can discuss some of the changes to fix this, and also get input from the addon developers. This should hopefully go through soon. 

As for this issue, reloading the chunks (f3 + a) will also quickly fix the issue. And if you have issues with ItemStages throwing the held item, it should still be in your hand but invisible in the client. Clicking the slot will fix the item being invisible.

**Comment by darkhax** [comment] 2018-05-21 01:05
This has been fixed in the 2.0.0 update.

**Closed by darkhax** 2018-05-21 01:05 UTC
Labels: bug
